import turtle
length = int(input())
height = int(input())
width = int (input())
turtle.forward(length)
turtle.left(90)
turtle.forward(height)
turtle.left(90)
turtle.backward(-height)
turtle.left(90)
turtle.backward(-length)
turtle.left(90)
turtle.forward(length)
turtle.left(45)
turtle.forward(width)
turtle.left(45)
turtle.forward(height)
turtle.left(135)
turtle.forward(width)
turtle.left(-45)
turtle.forward(length)
turtle.right(135)
turtle.forward(width)
turtle.right(135)
turtle.forward(height)
turtle.left(90)
turtle.forward(width)
turtle.left(90)
turtle.forward(height)
turtle.left(90)
turtle.forward(width)
turtle.left(90)
turtle.forward(height)
turtle.left(-45)
turtle.forward(length)


